services:
  - type: web
    name: travel-agent-app
    env: docker
    plan: free
    region: ohio
    envVars:
      - key: APP_KEY
        value: base64:N1MCJL056UWrgHpoupRab/9cm9jFPJS8OjuiET714FI=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        # We will leave this blank to let Render use its automatic subdomains
        value: ""
      - key: DB_CONNECTION
        value: sqlite
      - key: DUFFEL_ACCESS_TOKEN
        value: ""
