<x-admin-layout>
    <x-slot name="title">Support Center</x-slot><x-slot name="pageTitle">Support Center</x-slot><x-slot name="pageSubtitle">One calm inbox for every customer and partner</x-slot>
    <div class="space-y-6">
        <div class="grid sm:grid-cols-3 gap-4">
            @foreach([['unassigned','Unassigned',$counts['unassigned'],'fa-inbox','bg-violet-50 text-violet-600'],['mine','Assigned to me',$counts['mine'],'fa-user-check','bg-blue-50 text-blue-600'],['urgent','Urgent',$counts['urgent'],'fa-bolt','bg-red-50 text-[#d00e15]']] as [$key,$label,$count,$icon,$color])
                <a href="{{ route('admin.support.index',['queue'=>$key]) }}" class="bg-white border {{ $queue===$key ? 'border-[#d00e15] ring-2 ring-red-50' : 'border-gray-100' }} rounded-2xl p-5 flex items-center gap-4 shadow-sm hover:-translate-y-0.5 transition"><span class="h-12 w-12 rounded-2xl {{ $color }} flex items-center justify-center"><i class="fas {{ $icon }}"></i></span><span><strong class="text-2xl font-heading block">{{ $count }}</strong><small class="text-gray-500 font-semibold">{{ $label }}</small></span></a>
            @endforeach
        </div>
        <section class="bg-white rounded-3xl border border-gray-100 shadow-sm overflow-hidden">
            <div class="p-5 border-b border-gray-100 flex flex-col lg:flex-row gap-4 lg:items-center lg:justify-between">
                <div class="flex flex-wrap gap-2">@foreach(['all'=>'All','open'=>'Open','unassigned'=>'Unassigned','mine'=>'Mine','urgent'=>'Urgent','resolved'=>'Resolved'] as $key=>$label)<a href="{{ route('admin.support.index',['queue'=>$key]) }}" class="rounded-full px-3.5 py-2 text-xs font-bold {{ $queue===$key ? 'bg-[#19100F] text-white' : 'bg-gray-50 text-gray-500 hover:bg-gray-100' }}">{{ $label }}</a>@endforeach</div>
                <form class="relative"><input type="hidden" name="queue" value="{{ $queue }}"><i class="fas fa-search absolute left-4 top-3.5 text-gray-300"></i><input name="search" value="{{ request('search') }}" placeholder="Ticket, person or email…" class="w-full lg:w-72 rounded-xl border-gray-200 pl-10 text-sm"></form>
            </div>
            <div class="divide-y divide-gray-100">
                @forelse($tickets as $ticket)<a href="{{ route('admin.support.show',$ticket) }}" class="grid md:grid-cols-[1fr_150px_140px] gap-4 items-center p-5 hover:bg-red-50/30 transition"><div class="flex gap-4 min-w-0"><span class="relative h-11 w-11 rounded-2xl bg-gray-100 text-gray-500 flex items-center justify-center shrink-0"><i class="fas {{ $ticket->requester_type==='property_owner' ? 'fa-hotel' : 'fa-user' }}"></i>@if($ticket->isUnreadFor(auth()->user()))<span class="absolute -right-1 -top-1 h-3 w-3 rounded-full bg-[#d00e15] border-2 border-white"></span>@endif</span><div class="min-w-0"><div class="flex items-center gap-2"><h3 class="font-bold truncate">{{ $ticket->subject }}</h3>@if($ticket->priority==='urgent')<span class="text-[10px] font-bold text-[#d00e15] bg-red-50 rounded px-2 py-0.5">URGENT</span>@endif</div><p class="text-xs text-gray-400 mt-1">{{ $ticket->ticket_number }} · {{ $ticket->requester->name }} · {{ str($ticket->requester_type)->replace('_',' ')->title() }}</p></div></div><div><p class="text-xs text-gray-400">Assigned to</p><p class="text-sm font-semibold truncate">{{ $ticket->assignee->name ?? 'Unassigned' }}</p></div><div class="md:text-right"><span class="inline-flex rounded-full px-3 py-1 text-xs font-bold {{ in_array($ticket->status,['resolved','closed']) ? 'bg-emerald-50 text-emerald-700' : ($ticket->status==='waiting_for_customer' ? 'bg-amber-50 text-amber-700' : 'bg-blue-50 text-blue-700') }}">{{ str($ticket->status)->replace('_',' ')->title() }}</span><p class="text-[11px] text-gray-400 mt-2">{{ $ticket->last_message_at->diffForHumans() }}</p></div></a>
                @empty<div class="py-16 text-center"><i class="far fa-circle-check text-4xl text-emerald-400"></i><h3 class="font-bold text-lg mt-4">This queue is clear</h3><p class="text-sm text-gray-400 mt-1">Nothing needs your attention here.</p></div>@endforelse
            </div>
        </section>{{ $tickets->links() }}
    </div>
</x-admin-layout>
