<x-dynamic-component :component="$layout">
    <x-slot name="title">New support request</x-slot><x-slot name="pageTitle">New support request</x-slot><x-slot name="pageSubtitle">Share the details—we’ll take it from here</x-slot>
    <div class="max-w-3xl mx-auto">
        <a href="{{ route($routePrefix.'.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-gray-500 hover:text-[#d00e15] mb-5"><i class="fas fa-arrow-left"></i> Back to support</a>
        <form method="POST" action="{{ route($routePrefix.'.store') }}" enctype="multipart/form-data" class="bg-white rounded-3xl border border-gray-100 shadow-sm p-6 md:p-8 space-y-6">
            @csrf
            <div><h2 class="font-heading font-bold text-2xl">What can we help with?</h2><p class="text-gray-500 text-sm mt-1">Choose the closest topic so your request reaches the right person.</p></div>
            @if($errors->any())<div class="rounded-2xl bg-red-50 border border-red-100 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
            <div class="grid md:grid-cols-2 gap-5">
                <label class="block"><span class="text-sm font-bold text-gray-700">Topic</span><select name="category" required class="mt-2 w-full rounded-xl border-gray-200 focus:border-[#d00e15] focus:ring-[#d00e15]"><option value="">Choose a topic</option>@foreach($categories as $value=>$label)<option value="{{ $value }}" @selected(old('category')===$value)>{{ $label }}</option>@endforeach</select></label>
                <label class="block"><span class="text-sm font-bold text-gray-700">Priority</span><select name="priority" required class="mt-2 w-full rounded-xl border-gray-200 focus:border-[#d00e15] focus:ring-[#d00e15]"><option value="low">Low — general question</option><option value="normal" selected>Normal — need some help</option><option value="high">High — trip or business affected</option><option value="urgent">Urgent — immediate travel issue</option></select></label>
            </div>
            @if($properties->isNotEmpty())<label class="block"><span class="text-sm font-bold text-gray-700">Related property <span class="font-normal text-gray-400">(optional)</span></span><select name="property_id" class="mt-2 w-full rounded-xl border-gray-200"><option value="">No specific property</option>@foreach($properties as $property)<option value="{{ $property->id }}">{{ $property->name }}</option>@endforeach</select></label>@endif
            @if($bookings->isNotEmpty())<label class="block"><span class="text-sm font-bold text-gray-700">Related booking <span class="font-normal text-gray-400">(optional)</span></span><select name="booking_id" class="mt-2 w-full rounded-xl border-gray-200"><option value="">No specific booking</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}">#{{ $booking->booking_reference ?? $booking->id }} · {{ optional($booking->property)->name ?? 'Booking' }}</option>@endforeach</select></label>@endif
            <label class="block"><span class="text-sm font-bold text-gray-700">Subject</span><input name="subject" value="{{ old('subject') }}" required maxlength="180" placeholder="A short summary of the issue" class="mt-2 w-full rounded-xl border-gray-200 focus:border-[#d00e15] focus:ring-[#d00e15]"></label>
            <label class="block"><span class="text-sm font-bold text-gray-700">Tell us what happened</span><textarea name="message" required rows="7" maxlength="10000" placeholder="Include any details that will help us understand and solve the issue…" class="mt-2 w-full rounded-xl border-gray-200 focus:border-[#d00e15] focus:ring-[#d00e15]">{{ old('message') }}</textarea></label>
            <label class="block rounded-2xl border-2 border-dashed border-gray-200 p-5 hover:border-[#d00e15]/50 transition cursor-pointer"><span class="flex items-center gap-3"><span class="h-10 w-10 rounded-xl bg-gray-100 flex items-center justify-center text-gray-500"><i class="fas fa-paperclip"></i></span><span><strong class="block text-sm">Add screenshots or documents</strong><small class="text-gray-400">Up to 5 files, 5 MB each · JPG, PNG, WebP, PDF, DOC</small></span></span><input type="file" name="attachments[]" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx" class="mt-3 text-sm text-gray-500"></label>
            <div class="flex justify-end"><button class="rounded-2xl bg-[#d00e15] px-6 py-3 text-white font-bold shadow-lg shadow-red-200 hover:bg-[#b50b12] transition"><i class="fas fa-paper-plane mr-2"></i> Send request</button></div>
        </form>
    </div>
</x-dynamic-component>
