<x-dynamic-component :component="$layout">
    <x-slot name="title">{{ $ticket->ticket_number }}</x-slot><x-slot name="pageTitle">Support conversation</x-slot><x-slot name="pageSubtitle">{{ $ticket->ticket_number }}</x-slot>
    <div class="max-w-5xl mx-auto">
        <a href="{{ route($routePrefix.'.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-gray-500 hover:text-[#d00e15] mb-5"><i class="fas fa-arrow-left"></i> All conversations</a>
        <div class="grid lg:grid-cols-[1fr_260px] gap-6 items-start">
            <section class="bg-white rounded-3xl border border-gray-100 shadow-sm overflow-hidden">
                <header class="p-5 md:p-6 border-b border-gray-100 flex items-start justify-between gap-4"><div><h2 class="font-heading text-xl font-bold">{{ $ticket->subject }}</h2><p class="text-sm text-gray-400 mt-1">Started {{ $ticket->created_at->format('d M Y, g:i A') }}</p></div><span class="rounded-full px-3 py-1 text-xs font-bold {{ in_array($ticket->status,['resolved','closed']) ? 'bg-emerald-50 text-emerald-700' : 'bg-blue-50 text-blue-700' }}">{{ str($ticket->status)->replace('_',' ')->title() }}</span></header>
                <div id="conversation" class="p-5 md:p-7 space-y-6 bg-[#fbfbfc] min-h-[360px]">
                    @foreach($ticket->messages as $message)
                        @php($mine = $message->sender_id === auth()->id())
                        <div class="flex gap-3 {{ $mine ? 'justify-end' : '' }}">@unless($mine)<div class="h-9 w-9 rounded-xl bg-[#19100F] text-white flex items-center justify-center text-xs font-bold shrink-0">G</div>@endunless<div class="max-w-[82%]"><div class="rounded-2xl px-4 py-3 {{ $mine ? 'bg-[#d00e15] text-white rounded-br-md' : 'bg-white border border-gray-100 text-gray-700 rounded-bl-md shadow-sm' }}"><p class="text-sm whitespace-pre-wrap leading-relaxed">{{ $message->body }}</p>@if($message->attachments->isNotEmpty())<div class="mt-3 space-y-2">@foreach($message->attachments as $attachment)<a href="{{ route('support.attachments.download',$attachment) }}" class="flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-semibold {{ $mine ? 'bg-white/15 hover:bg-white/20' : 'bg-gray-50 hover:bg-gray-100' }}"><i class="fas fa-paperclip"></i><span class="truncate">{{ $attachment->original_name }}</span></a>@endforeach</div>@endif</div><p class="text-[11px] text-gray-400 mt-1 {{ $mine ? 'text-right' : '' }}">{{ $mine ? 'You' : 'Bookdei Support' }} · {{ $message->created_at->format('d M, g:i A') }}</p></div></div>
                    @endforeach
                </div>
                @if($ticket->status !== 'closed')<form method="POST" action="{{ route($routePrefix.'.reply',$ticket) }}" enctype="multipart/form-data" class="p-4 md:p-5 border-t border-gray-100">@csrf<div class="rounded-2xl border border-gray-200 focus-within:border-[#d00e15] focus-within:ring-2 focus-within:ring-red-50"><textarea name="message" required rows="3" maxlength="10000" placeholder="Write a message…" class="w-full resize-none border-0 rounded-2xl focus:ring-0 text-sm"></textarea><div class="flex items-center justify-between px-3 pb-3"><label class="cursor-pointer text-gray-400 hover:text-[#d00e15]" title="Attach files"><i class="fas fa-paperclip"></i><input type="file" name="attachments[]" multiple class="hidden"></label><button class="rounded-xl bg-[#d00e15] px-5 py-2.5 text-white text-sm font-bold">Send <i class="fas fa-paper-plane ml-1"></i></button></div></div></form>@endif
            </section>
            <aside class="space-y-4"><div class="bg-white rounded-2xl border border-gray-100 p-5"><h3 class="text-xs font-bold uppercase tracking-wider text-gray-400">Request details</h3><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-gray-400">Topic</dt><dd class="font-semibold">{{ $categories[$ticket->category] ?? str($ticket->category)->headline() }}</dd></div><div><dt class="text-gray-400">Priority</dt><dd class="font-semibold capitalize">{{ $ticket->priority }}</dd></div>@if($ticket->property)<div><dt class="text-gray-400">Property</dt><dd class="font-semibold">{{ $ticket->property->name }}</dd></div>@endif<div><dt class="text-gray-400">Support agent</dt><dd class="font-semibold">{{ $ticket->assignee->name ?? 'Being assigned' }}</dd></div></dl></div>
            @if(in_array($ticket->status,['resolved','closed']) && !$ticket->rating)<form method="POST" action="{{ route($routePrefix.'.rate',$ticket) }}" class="bg-white rounded-2xl border border-gray-100 p-5">@csrf<h3 class="font-bold">How did we do?</h3><p class="text-xs text-gray-400 mt-1">Rate this support experience.</p><div class="flex gap-1 mt-4">@foreach(range(1,5) as $star)<label class="cursor-pointer"><input type="radio" name="rating" value="{{ $star }}" class="sr-only peer" required><i class="fas fa-star text-2xl text-gray-200 peer-checked:text-amber-400 hover:text-amber-300"></i></label>@endforeach</div><button class="mt-4 text-sm font-bold text-[#d00e15]">Submit feedback</button></form>@endif</aside>
        </div>
    </div>
    @push('scripts')<script>document.getElementById('conversation')?.lastElementChild?.scrollIntoView({block:'nearest'});</script>@endpush
</x-dynamic-component>
